### ISSUE TITLE
Gotify 

### ISSUE THREAD

**Issue by EVOTk** [crobibero/jellyfin-plugin-webhook#17] opened 2021-03-15 12:32 UTC
Hello,

I installed the Webhook plugins with the Gotify template.
I checked to be notified when an episode / movie is launched, ...

I do receive the notification at the start of the episode, but on the other hand, it indicates "has been added to Jellyfin Server".
It will be more accurate to indicate "has been started in Jellyfin Server" or "is played in Jellyfin Server", no?

The message is also the same if the video is stopped with the "Playback Stop" setting.

Big Thx

"Playback Start"
![Gotify](https://i.imgur.com/g2a9bMJ.png)

"Playback Stop"
![Gotify](https://i.imgur.com/4kWhINp.png)

**Comment by crobibero** [comment] 2021-03-15 12:36
Duplicate of https://github.com/crobibero/jellyfin-plugin-webhook/issues/16

you have to change the template.

**Closed by crobibero** 2021-03-15 12:36 UTC

**Comment by EVOTk** [comment] 2021-03-15 12:40
Perfect , thx
Sorry I did not see the other issues!
